server:
    port: 8000
    #context-path: /boot
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.201.28:3306/frontshopping
#    username: shopping_user
#    password: shopping_user
#    driver-class-name: com.mysql.jdbc.Driver
#    type: org.apache.commons.dbcp.BasicDataSource
#    dbcp2:
#      validation-query: SELECT NOW() FROM DUAL
#      test-on-borrow: true
#mybatis:
#  #mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.lxh.cloud.study.model
#management:
#  security:
#    enabled: false
#user:
#  userServiceUrl: http://localhost/user/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true
#microservice-provider-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
#    com.lxh.cloud.study.user.feign.UserFeignClient: DEBUG
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
feign:
  hystrix:
    enabled: true